Added new functions to owm-update

diff --git a/usr/sbin/owm-update b/usr/sbin/owm-update
--- a/usr/sbin/owm-update
+++ b/usr/sbin/owm-update
@@ -1,11 +1,45 @@
 #!/bin/sh
 # OpenWifiMap updater script
 # By CyrusFox, basic hacked version ;)
+# Utilizes libubox's jshn.sh 
+# Sadly the current (AA 12.09) package version doesnt support double types
+# therefore it will be limited to basic data + postalAddress + interfaces
+# For necessary stuff like latitude and longitude the json request is build
+# with echo ;)
 
 fail() {
     echo "$1" 1>&2
     exit 1
 }
+
+get_iface () {
+	local interface=$1
+	local iface=$(uci get network.$interface.ifname)
+	local type=$(uci -q get network.$interface.type)
+	[ "bridge" = "$type" ] && iface="br-$interface"
+	echo $iface
+}
+
+mask2cidr() {
+    nbits=0
+    IFS=.
+    for dec in $1 ; do
+        case $dec in
+            255) let nbits+=8;;
+            254) let nbits+=7;;
+            252) let nbits+=6;;
+            248) let nbits+=5;;
+            240) let nbits+=4;;
+            224) let nbits+=3;;
+            192) let nbits+=2;;
+            128) let nbits+=1;;
+            0);;
+            *) echo "Error: $dec is not recognised"; exit 1
+        esac
+    done
+    echo "$nbits"
+}
+
 
 get_rev() {
 	echo -e "HEAD /openwifimap/$nodeid HTTP/1.1\r
@@ -45,15 +79,157 @@ $(cat /tmp/map/$host.json)\r
 " | netcat -v -w 1 $map_server 80 > /tmp/owm_update
 	fi
 }
-update_map() {
-	local host=$(cat /proc/sys/kernel/hostname) 
+
+generate_json_postalAddress() {
+	# Postal Address section
+	local postal_name=$(uci -q get owm.settings.postal_name)
+	local postal_street=$(uci -q get owm.settings.postal_street)
+	local postal_zip=$(uci -q get owm.settings.postal_zip)
+	local postal_city=$(uci -q get owm.settings.postal_city)
+	local postal_country=$(uci -q get owm.settings.postal_country)
+
+	if [ -n "$postal_name" \
+		-o -n "$postal_street" \
+		-o -n "$postal_zip" \
+		-o -n "$postal_city" \
+		-o -n "$postal_country" ]; then
+		postalAddress=$(
+			. /usr/share/libubox/jshn.sh
+			json_init 
+			[ -n "$postal_name" ] && json_add_string "name" "$postal_name"
+			[ -n "$postal_street" ] && json_add_string "street" "$postal_street"
+			[ -n "$postal_zip" ] && json_add_string "zip" "$postal_zip"
+			[ -n "$postal_city" ] && json_add_string "city" "$postal_city"
+			[ -n "$postal_country" ] && json_add_string "country" "$postal_country"
+			echo $(json_dump)
+		)
+		echo "$postalAddress"
+	fi
+}
+
+generate_json_interfaces() {
+	# Wired / Batman / Mesh Interfaces section
+	#interfaces=$(uci -q get owm.settings.interfaces)
+	local interfaces="lan wan mesh"
+	
+	
+	for interface in $interfaces 
+	do
+		if [ "$(ubus call network.interface.$interface status | grep '"up"': | cut -d ' ' -f2 | cut -d ',' -f1)" == "true" ]; then
+			#Get stuff
+			local l3_device=$(get_iface $interface)
+			local macaddr=$(ubus call network.device status '{ "name": "'$l3_device'" }' | grep "macaddr" | cut -d '"' -f4)
+			local name=$interface
+			local ip4addr=$(ifconfig $l3_device | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
+			local ip4mask=$(mask2cidr $(ifconfig $l3_device | grep Mask | sed s/^.*Mask://))
+			local ip6addrs=$(ifconfig $l3_device | awk '/inet6 addr/ {print $3}')
+			local jsondata=$(
+			. /usr/share/libubox/jshn.sh
+			json_init 
+			json_add_string "name" "$name"
+			json_add_string "physicalType" "ethernet"
+			json_add_string "macAddress" "$macaddr"
+			if [ -n "$ip4addr" -a -n "$ip4mask" ]; then
+				json_add_array ipv4Addresses
+				json_add_string 0 "$ip4addr/$ip4mask"
+				json_close_array
+			fi
+			if [ -n "$ip6addrs" ]; then
+				json_add_array ipv6Addresses
+				for ip6addr in $ip6addrs
+				do
+					json_add_string 0 "$ip6addr"
+				done
+				json_close_array
+			fi
+			echo $(json_dump)
+			)
+			echo $jsondata >> /tmp/map/interfaces/"$interface"-iface.json
+		fi
+		done
+	interface_count=$(ls -l /tmp/map/interfaces/ | grep iface.json | wc -l)
+	counter="1"
+	for jsonfile in $(find /tmp/map/interfaces/ | grep iface.json)
+	do
+		cat $jsonfile >> /tmp/map/interfaces/all.json
+		counter_new=`expr $counter + 1`
+		if [ "$counter_new" -le "$interface_count" ]; then
+			echo ',' >> /tmp/map/interfaces/all.json
+		fi
+		counter="$counter_new"
+	done
+	echo $(cat /tmp/map/interfaces/all.json)
+
+}
+
+generate_json_ipv4defaultGateway() {
+	local defroute=$(route -n | grep ^0.0.0.0)
+	local defroute_gw=$(echo $defroute | awk '{print $2}')
+	local defroute_metric=$(echo $defroute | awk '{print $5}')
+	local defroute_iface=$(echo $defroute | awk '{print $8}')
+	
+	if [ -n "$defroute" ]; then
+	
+	local jsondata=$(
+			. /usr/share/libubox/jshn.sh
+			json_init 
+			json_add_string gateway "$defroute_gw"
+			json_add_string dev "$defroute_iface"
+			json_add_string metr "$defroute_metric"
+			echo $(json_dump)
+			)
+			
+	echo $jsondata
+	fi
+}
+
+generate_json_ipv6defaultGateway() {
+	local defroute=$(route -n -A inet6 | grep ^::/0)
+	local defroute_gw=$(echo $defroute | awk '{print $2}')
+	local defroute_metric=$(echo $defroute | awk '{print $4}')
+	local defroute_iface=$(echo $defroute | awk '{print $7}')
+	
+	if [ -n "$defroute" ]; then
+	
+	local jsondata=$(
+			. /usr/share/libubox/jshn.sh
+			json_init 
+			json_add_string gateway "$defroute_gw"
+			json_add_string dev "$defroute_iface"
+			json_add_string metr "$defroute_metric"
+			echo $(json_dump)
+			)
+			
+	echo $jsondata
+	fi
+}
+
+generate_json () {
+	#Add basic (necessary) stuff
+	echo '{"type": "node", "hostname": "'$host.$zonename'", "longitude": '$lon', "latitude": '$lat', "updateInterval": '$interval',' > /tmp/map/"$host".json
+	#Add postal (Dude) stuff :D
+	postalData=$(generate_json_postalAddress)
+	[ -n "$postalData" ] && echo '"postalAddress": '$postalData',' >> /tmp/map/"$host".json
+	#Add interfaces
+	interfacesData=$(generate_json_interfaces)
+	[ -n "$interfacesData" ] && echo '"interfaces": ['$interfacesData'],' >> /tmp/map/"$host".json
+	#Add default routes
+	ip4defroute=$(generate_json_ipv4defaultGateway)
+	[ -n "$ip4defroute" ] && echo '"ipv4defaultGateway": '$ip4defroute','  >> /tmp/map/"$host".json
+	ip6defroute=$(generate_json_ipv6defaultGateway)
+	[ -n "$ip6defroute" ] && echo '"ipv6defaultGateway": '$ip6defroute','  >> /tmp/map/"$host".json
+	
+	echo '"lastupdate": "'$(date -u "+%Y-%m-%dT%H:%M:%SZ")'"}'  >> /tmp/map/"$host".json
+}
+
+update() {
 	if [ $(uci -q get owm.settings.public) == "true" -a $host != "ffnode" ]; then
-	mkdir -p /tmp/map
-	echo "Update node $host.$zonename on server $map_server"
-	echo '{"type": "node", "hostname": "'$host.$zonename'", "longitude": '$lon', "latitude": '$lat', "lastupdate": "'$(date -u "+%Y-%m-%dT%H:%M:%SZ")'", "updateInterval": '$interval'}' > /tmp/map/"$host".json
-	send_update
+		logger -t owm-update "Update node $host.$zonename on server $map_server"
+		generate_json
+		#echo $(cat /tmp/map/"$host".json)
+		send_update
 	else
-		echo "Node is private or hostname is not set, not updating..."
+		logger -t owm-update "Node is private or hostname is not set, not updating..."
 	fi
 }
 
@@ -61,7 +237,7 @@ update_map() {
 
 printArgs () {
     fail "Usage:
-$0 update_map
+$0 update_map or update
 "
 }
 [ $# -lt 1 ] && printArgs
@@ -72,6 +248,7 @@ lat=$(uci -q get owm.settings.lat)
 lon=$(uci -q get owm.settings.lon)
 map_server=$(uci -q get owm.settings.map_server)
 nodeid=$(cat /etc/nodeid)
+host=$(cat /proc/sys/kernel/hostname) 
 
 [ -z $interval ] && fail "Interval not set in OWM config"
 [ -z $zonename ] && fail "Zonename not set in OWM config"
@@ -79,11 +256,15 @@ nodeid=$(cat /etc/nodeid)
 [ -z $map_server ] && fail "Map server not set in OWM config"
 [ -z $nodeid ] && fail "NodeID not set yet, please wait for NodeID script to run.."
 
+[ -d "/tmp/map/interfaces" ] || mkdir -p /tmp/map/interfaces
+rm -f /tmp/map/*.json
+rm -f /tmp/map/interfaces/*.json
+
 case "$1" in
-  --help|-h)
-    printArgs
+  update|update_map)
+    update
     ;;
   *)
-    update_map
+	printArgs
     ;;
 esac
